pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
             //   sh 'mvn -B -DskipTests clean package'
                   bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                //sh 'mvn test'
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}
